In [1]:
from arm import *

In [2]:
range_limiter = do.Range_Limiter_Scalar(0, np.pi)

In [3]:
range_limiter.map_scalar_to_target_interval(-100)

1.1686963357062937e-43

In [4]:
range_limiter.map_scalar_to_target_interval(100)

3.141592653589793

In [5]:
range_limiter.derivative_of_mapping(10)

0.00014260866166367913

In [6]:
range_limiter.derivative_of_mapping(0)

0.39269908169872414

In [7]:
range_limiter.derivative_of_mapping(-5)

0.00013978344426319542

In [8]:
range_limiter_vector = do.Range_Limit_Vector((
    (0, 2*np.pi),
    (0, np.pi),
    (0, np.pi),
    (0, np.pi),
))

In [9]:
range_limiter_vector.function(
    np.array([0,0,0,0])
)

array([3.14159265, 1.57079633, 1.57079633, 1.57079633])

In [10]:
range_limiter_vector.derivative_WR_vector(
    np.array([0,0,0,0])
)

array([[0.78539816, 0.        , 0.        , 0.        ],
       [0.        , 0.39269908, 0.        , 0.        ],
       [0.        , 0.        , 0.39269908, 0.        ],
       [0.        , 0.        , 0.        , 0.39269908]])

In [11]:
arm = Leipzig_Robot_Arm()

In [12]:
arm.get_GP_position_at_angles(
    np.array([0, np.pi/2, np.pi/2, np.pi/2])
)

array([0., 0., 7.])

In [13]:
arm.get_GP_position_at_angles(
    np.array([np.pi, np.pi/2, np.pi/2, np.pi/2])
)

array([0., 0., 7.])

In [14]:
arm.get_GP_position_at_angles(
    np.array([0, np.pi/2, np.pi/2, np.pi])
)

array([-1.0000000e+00,  1.2246468e-16,  6.0000000e+00])

In [15]:
angles = range_limiter_vector.function([0,0,0,0])
angles

array([3.14159265, 1.57079633, 1.57079633, 1.57079633])

In [16]:
np.array([0, np.pi/2, np.pi/2, np.pi/2])

array([0.        , 1.57079633, 1.57079633, 1.57079633])

In [17]:
arm.get_GP_position_at_angles(angles)

array([0., 0., 7.])

In [18]:
desired_position = np.array([0., 0., 7.])
angles_estimate = arm.get_angles_for_GP_position(desired_position, echo_level = 2)
achieved_position = arm.get_GP_position_at_angles(angles_estimate)
achieved_position

Iteration 0: Current loss is:  0.000000000000 with learning rate:   0.20000000
Starting Angles: [3.1416, 1.5708, 1.5708, 1.5708]:
Current Angles are:  [3.1416, 1.5708, 1.5708, 1.5708]
Desired position is:  [0.0, 0.0, 7.0]
Current position is:  [0.0, 0.0, 7.0]
Current loss is:  0.0


array([0., 0., 7.])

In [19]:
some_angles = np.array([np.pi/4, np.pi/2, np.pi/2, 0.01])
desired_position = arm.get_GP_position_at_angles(some_angles)
desired_position

array([0.70707143, 0.70707143, 6.00999983])

In [20]:
angles_estimate = arm.get_angles_for_GP_position(desired_position, echo_level = 2)
achieved_position = arm.get_GP_position_at_angles(angles_estimate)
achieved_position

Iteration 0: Current loss is:  1.980000333332 with learning rate:   0.20000000
Iteration 99: Current loss is:  0.086110306996 with learning rate:   0.20000000
Iteration 199: Current loss is:  0.002778336415 with learning rate:   0.20000000
Iteration 299: Current loss is:  0.000093827405 with learning rate:   0.20000000
Iteration 399: Current loss is:  0.000003154839 with learning rate:   0.20000000
Iteration 499: Current loss is:  0.000000107532 with learning rate:   0.20000000
Starting Angles: [3.1416, 1.5708, 1.5708, 1.5708]:
Current Angles are:  [3.927, 1.4126, 1.9704, 2.7944]
Desired position is:  [0.7071, 0.7071, 6.01]
Current position is:  [0.7071, 0.7071, 6.0101]
Current loss is:  9.736841750687405e-09


array([0.70707044, 0.7071052 , 6.01009089])

# I think the above is a great example of a local minima. I think it is locally if change the j component without increasing loss.
# I will try adding in the tries mechanism to fix this

In [21]:
some_angles = np.array([np.pi/3, 4*np.pi/5, np.pi/7, 3*np.pi/4])
some_angles

array([1.04719755, 2.51327412, 0.44879895, 2.35619449])

In [22]:
desired_position = arm.get_GP_position_at_angles(some_angles)
desired_position

array([-1.31971084, -2.28580623,  5.55321701])

In [23]:
angles_estimated_from_position = arm.get_angles_for_GP_position(desired_position, echo_level=2)
angles_estimated_from_position

Iteration 0: Current loss is:  9.059727861736 with learning rate:   0.20000000
Iteration 99: Current loss is:  0.003746779866 with learning rate:   0.20000000
Iteration 199: Current loss is:  0.000632916173 with learning rate:   0.20000000
Iteration 299: Current loss is:  0.000262470905 with learning rate:   0.20000000
Iteration 399: Current loss is:  0.000150672733 with learning rate:   0.20000000
Iteration 499: Current loss is:  0.000043918073 with learning rate:   0.20000000
Iteration 599: Current loss is:  0.000007193525 with learning rate:   0.20000000
Iteration 699: Current loss is:  0.000002270436 with learning rate:   0.20000000
Iteration 799: Current loss is:  0.000001388827 with learning rate:   0.20000000
Iteration 899: Current loss is:  0.000000482283 with learning rate:   0.20000000
Iteration 999: Current loss is:  0.000000087833 with learning rate:   0.20000000
Iteration 1099: Current loss is:  0.000000019892 with learning rate:   0.20000000
Starting Angles: [3.1416, 1.57

array([1.04716653, 1.71111929, 2.0864245 , 2.48792348])

In [24]:
resulting_position = arm.get_GP_position_at_angles(angles_estimated_from_position)
resulting_position

array([-1.31977722, -2.28575747,  5.55316704])