In [1]:
from arm import *
from differential_operations import *

In [2]:
range_limiter = Range_Limiter(0, pi)

In [3]:
range_limiter.map_scalar_to_target_interval(-100)

1.1686963357062937e-43

In [4]:
range_limiter.map_scalar_to_target_interval(100)

3.141592653589793

In [5]:
range_limiter.derivative_of_mapping(10)

0.00014260866166367913

In [6]:
range_limiter.derivative_of_mapping(0)

0.39269908169872414

In [7]:
range_limiter.derivative_of_mapping(-5)

0.00013978344426319542

In [8]:
range_limiter_vector = Range_Limit_Vector((
    (0, 2*pi),
    (0, pi),
    (0, pi),
    (0, pi),
))

In [9]:
range_limiter_vector.map_vector_to_target_interval(
    np.array([0,0,0,0])
)

array([3.14159265, 1.57079633, 1.57079633, 1.57079633])

In [10]:
range_limiter_vector.derivative_of_mapping(
    np.array([0,0,0,0])
)

array([[0.78539816, 0.        , 0.        , 0.        ],
       [0.        , 0.39269908, 0.        , 0.        ],
       [0.        , 0.        , 0.39269908, 0.        ],
       [0.        , 0.        , 0.        , 0.39269908]])

In [11]:
arm = Leipzig_Robot_Arm()

In [12]:
arm.get_GP_position_at_angles(
    np.array([0, pi/2, pi/2, pi/2])
)

array([0., 0., 7.])

In [13]:
arm.get_GP_position_at_angles(
    np.array([pi, pi/2, pi/2, pi/2])
)

array([0., 0., 7.])

In [14]:
arm.get_GP_position_at_angles(
    np.array([0, pi/2, pi/2, pi])
)

array([-1.0000000e+00, -1.2246468e-16,  6.0000000e+00])

In [15]:
angles = range_limiter_vector.map_vector_to_target_interval([0,0,0,0])
angles

array([3.14159265, 1.57079633, 1.57079633, 1.57079633])

In [16]:
np.array([0, pi/2, pi/2, pi/2])

array([0.        , 1.57079633, 1.57079633, 1.57079633])

In [17]:
arm.get_GP_position_at_angles(angles)

array([0., 0., 7.])

In [18]:
desired_position = np.array([0., 0., 7.])
angles_estimate = arm.get_angles_for_GP_position(desired_position)
achieved_position = arm.get_GP_position_at_angles(angles_estimate)
achieved_position

array([0., 0., 7.])

In [19]:
some_angles = np.array([pi/4, pi/2, pi/2, 0.01])
desired_position = arm.get_GP_position_at_angles(some_angles)
desired_position

array([0.70707143, 0.70707143, 6.00999983])

In [20]:
angles_estimate = arm.get_angles_for_GP_position(desired_position)
achieved_position = arm.get_GP_position_at_angles(angles_estimate)
achieved_position

array([0.70706863, 0.70730766, 6.01025483])

In [21]:
some_angles = np.array([pi/3, 4*pi/5, pi/7, 3*pi/4])
some_angles

array([1.04719755, 2.51327412, 0.44879895, 2.35619449])

In [22]:
desired_position = arm.get_GP_position_at_angles(some_angles)
desired_position

array([-1.31971084, -2.28580623,  5.55321701])

In [23]:
angles_estimated_from_position = arm.get_angles_for_GP_position(desired_position)
angles_estimated_from_position

array([1.0327706 , 1.70628507, 2.09861234, 2.49749187])

In [24]:
resulting_position = arm.get_GP_position_at_angles(angles_estimated_from_position)
resulting_position

array([-1.35104615, -2.26401025,  5.52922696])