In [1]:
from arm import *

In [2]:
range_limiter = do.Range_Limiter_Scalar(0, pi)

In [3]:
range_limiter.map_scalar_to_target_interval(-100)

1.1686963357062937e-43

In [4]:
range_limiter.map_scalar_to_target_interval(100)

3.141592653589793

In [5]:
range_limiter.derivative_of_mapping(10)

0.00014260866166367913

In [6]:
range_limiter.derivative_of_mapping(0)

0.39269908169872414

In [7]:
range_limiter.derivative_of_mapping(-5)

0.00013978344426319542

In [8]:
range_limiter_vector = do.Range_Limit_Vector((
    (0, 2*pi),
    (0, pi),
    (0, pi),
    (0, pi),
))

In [9]:
range_limiter_vector.function(
    np.array([0,0,0,0])
)

array([3.14159265, 1.57079633, 1.57079633, 1.57079633])

In [10]:
range_limiter_vector.derivative_WR_vector(
    np.array([0,0,0,0])
)

array([[0.78539816, 0.        , 0.        , 0.        ],
       [0.        , 0.39269908, 0.        , 0.        ],
       [0.        , 0.        , 0.39269908, 0.        ],
       [0.        , 0.        , 0.        , 0.39269908]])

In [11]:
arm = Leipzig_Robot_Arm()

In [12]:
arm.get_GP_position_at_angles(
    np.array([0, pi/2, pi/2, pi/2])
)

array([0., 0., 7.])

In [13]:
arm.get_GP_position_at_angles(
    np.array([pi, pi/2, pi/2, pi/2])
)

array([0., 0., 7.])

In [14]:
arm.get_GP_position_at_angles(
    np.array([0, pi/2, pi/2, pi])
)

array([ 6.123234e-17, -1.000000e+00,  6.000000e+00])

In [15]:
angles = range_limiter_vector.function([0,0,0,0])
angles

array([3.14159265, 1.57079633, 1.57079633, 1.57079633])

In [16]:
np.array([0, pi/2, pi/2, pi/2])

array([0.        , 1.57079633, 1.57079633, 1.57079633])

In [17]:
arm.get_GP_position_at_angles(angles)

array([0., 0., 7.])

In [18]:
desired_position = np.array([0., 0., 7.])
angles_estimate = arm.get_angles_for_GP_position(desired_position)
achieved_position = arm.get_GP_position_at_angles(angles_estimate)
achieved_position

array([0., 0., 7.])

In [19]:
some_angles = np.array([pi/4, pi/2, pi/2, 0.01])
desired_position = arm.get_GP_position_at_angles(some_angles)
desired_position

array([-0.70707143,  0.70707143,  6.00999983])

In [20]:
angles_estimate = arm.get_angles_for_GP_position(desired_position, echo=True)
achieved_position = arm.get_GP_position_at_angles(angles_estimate)
achieved_position

Iteration 0:
Current angles are:   [1.6797, 1.5926, 1.5926, 1.5926]
Current position is:  [0.0, 0.0, 7.0]
Current loss is:  1.9800003333316667
Iteration 1:
Current angles are:   [1.8112, 1.5917, 1.5947, 1.5978]
Current position is:  [0.2168, 0.0237, 6.9952]
Current loss is:  2.291195515039257
Iteration 2:
Current angles are:   [1.9445, 1.5786, 1.5847, 1.5913]
Current position is:  [0.2175, 0.0533, 6.9948]
Current loss is:  2.2519868194905532
Iteration 3:
Current angles are:   [2.063, 1.5601, 1.5678, 1.5767]
Current position is:  [0.1013, 0.0397, 6.9985]
Current loss is:  2.0760970863379704
Iteration 4:
Current angles are:   [2.1579, 1.5405, 1.5478, 1.5571]
Current position is:  [-0.0591, -0.0317, 6.9996]
Current loss is:  1.944969696293099
Iteration 5:
Current angles are:   [2.228, 1.5218, 1.5271, 1.5351]
Current position is:  [-0.2204, -0.1466, 6.9935]
Current loss is:  1.9330121410922638
Iteration 6:
Current angles are:   [2.2763, 1.5056, 1.5075, 1.5127]
Current position is:  [-0.364

array([-0.7063997 , -0.70728205,  6.01473967])

# I think the above is a great example of a local minima. I think it is locally if change the j component without increasing loss.
# I will try adding in the tries mechanism to fix this

In [21]:
some_angles = np.array([pi/3, 4*pi/5, pi/7, 3*pi/4])
some_angles

array([1.04719755, 2.51327412, 0.44879895, 2.35619449])

In [22]:
desired_position = arm.get_GP_position_at_angles(some_angles)
desired_position

array([ 2.28580623, -1.31971084,  5.55321701])

In [23]:
angles_estimated_from_position = arm.get_angles_for_GP_position(desired_position)
angles_estimated_from_position

array([1.04719755, 1.70691054, 2.09856243, 2.47196195])

In [24]:
resulting_position = arm.get_GP_position_at_angles(angles_estimated_from_position)
resulting_position

array([ 2.28580623, -1.31971084,  5.55321701])