In [1]:
from arm import *

In [2]:
range_limiter = do.Range_Limiter_Scalar(0, np.pi)

In [3]:
range_limiter.map_scalar_to_target_interval(-100)

1.1686963357062937e-43

In [4]:
range_limiter.map_scalar_to_target_interval(100)

3.141592653589793

In [5]:
range_limiter.derivative_of_mapping(10)

0.00014260866166367913

In [6]:
range_limiter.derivative_of_mapping(0)

0.39269908169872414

In [7]:
range_limiter.derivative_of_mapping(-5)

0.00013978344426319542

In [8]:
range_limiter_vector = do.Range_Limit_Vector((
    (0, 2*np.pi),
    (0, np.pi),
    (0, np.pi),
    (0, np.pi),
))

In [9]:
range_limiter_vector.function(
    np.array([0,0,0,0])
)

array([3.14159265, 1.57079633, 1.57079633, 1.57079633])

In [10]:
range_limiter_vector.derivative_WR_vector(
    np.array([0,0,0,0])
)

array([[0.78539816, 0.        , 0.        , 0.        ],
       [0.        , 0.39269908, 0.        , 0.        ],
       [0.        , 0.        , 0.39269908, 0.        ],
       [0.        , 0.        , 0.        , 0.39269908]])

In [11]:
arm = Leipzig_Robot_Arm()

In [12]:
arm.get_GP_position_at_angles(
    np.array([0, np.pi/2, np.pi/2, np.pi/2])
)

array([0., 0., 7.])

In [13]:
arm.get_GP_position_at_angles(
    np.array([np.pi, np.pi/2, np.pi/2, np.pi/2])
)

array([0., 0., 7.])

In [14]:
arm.get_GP_position_at_angles(
    np.array([0, np.pi/2, np.pi/2, np.pi])
)

array([-1.8369702e-16, -1.0000000e+00,  6.0000000e+00])

In [15]:
angles = range_limiter_vector.function([0,0,0,0])
angles

array([3.14159265, 1.57079633, 1.57079633, 1.57079633])

In [16]:
np.array([0, np.pi/2, np.pi/2, np.pi/2])

array([0.        , 1.57079633, 1.57079633, 1.57079633])

In [17]:
arm.get_GP_position_at_angles(angles)

array([0., 0., 7.])

In [18]:
desired_position = np.array([0., 0., 7.])
angles_estimate = arm.get_angles_for_GP_position(desired_position)
achieved_position = arm.get_GP_position_at_angles(angles_estimate)
achieved_position

array([0., 0., 7.])

In [19]:
some_angles = np.array([np.pi/4, np.pi/2, np.pi/2, 0.01])
desired_position = arm.get_GP_position_at_angles(some_angles)
desired_position

array([-0.70707143,  0.70707143,  6.00999983])

In [20]:
angles_estimate = arm.get_angles_for_GP_position(desired_position, echo=True)
achieved_position = arm.get_GP_position_at_angles(angles_estimate)
achieved_position

Starting Angles: [0.84490439 0.84490439 0.84490439 0.84490439]:
Current Angles are:  [2.3556, 1.0371, 1.923, 2.843]
Desired position is:  [-0.7071, 0.7071, 6.01]
Current position is:  [-0.7078, -0.7069, 6.0119]
Current loss is:  1.999182920672167
Starting Angles: [1.57079633 1.57079633 1.57079633 1.57079633]:
Current Angles are:  [2.3568, 1.7975, 0.9877, 0.5754]
Desired position is:  [-0.7071, 0.7071, 6.01]
Current position is:  [-0.7064, -0.7073, 6.0149]
Current loss is:  2.0004387991347437
Starting Angles: [2.29668826 2.29668826 2.29668826 2.29668826]:
Current Angles are:  [2.3559, 1.6123, 0.6129, 2.968]
Desired position is:  [-0.7071, 0.7071, 6.01]
Current position is:  [-0.7072, -0.7067, 6.1022]
Current loss is:  2.0072681895118736


array([-0.70774498, -0.70685877,  6.01186072])

# I think the above is a great example of a local minima. I think it is locally if change the j component without increasing loss.
# I will try adding in the tries mechanism to fix this

In [21]:
some_angles = np.array([np.pi/3, 4*np.pi/5, np.pi/7, 3*np.pi/4])
some_angles

array([1.04719755, 2.51327412, 0.44879895, 2.35619449])

In [22]:
desired_position = arm.get_GP_position_at_angles(some_angles)
desired_position

array([ 2.28580623, -1.31971084,  5.55321701])

In [23]:
angles_estimated_from_position = arm.get_angles_for_GP_position(desired_position)
angles_estimated_from_position

array([1.04719755, 1.66377441, 2.23002439, 2.28337961])

In [24]:
resulting_position = arm.get_GP_position_at_angles(angles_estimated_from_position)
resulting_position

array([ 2.28580623, -1.31971084,  5.55321701])