In [1]:
from arm import *

In [2]:
range_limiter = do.Range_Limiter_Scalar(0, np.pi)

In [3]:
range_limiter.map_scalar_to_target_interval(-100)

1.1686963357062937e-43

In [4]:
range_limiter.map_scalar_to_target_interval(100)

3.141592653589793

In [5]:
range_limiter.derivative_of_mapping(10)

0.00014260866166367913

In [6]:
range_limiter.derivative_of_mapping(0)

0.39269908169872414

In [7]:
range_limiter.derivative_of_mapping(-5)

0.00013978344426319542

In [8]:
range_limiter_vector = do.Range_Limit_Vector((
    (0, 2*np.pi),
    (0, np.pi),
    (0, np.pi),
    (0, np.pi),
))

In [9]:
range_limiter_vector.function(
    np.array([0,0,0,0])
)

array([3.14159265, 1.57079633, 1.57079633, 1.57079633])

In [10]:
range_limiter_vector.derivative_WR_vector(
    np.array([0,0,0,0])
)

array([[0.78539816, 0.        , 0.        , 0.        ],
       [0.        , 0.39269908, 0.        , 0.        ],
       [0.        , 0.        , 0.39269908, 0.        ],
       [0.        , 0.        , 0.        , 0.39269908]])

In [11]:
arm = Leipzig_Robot_Arm()

In [12]:
arm.get_GP_position_at_angles(
    np.array([0, np.pi/2, np.pi/2, np.pi/2])
)

array([0., 0., 7.])

In [13]:
arm.get_GP_position_at_angles(
    np.array([np.pi, np.pi/2, np.pi/2, np.pi/2])
)

array([0., 0., 7.])

In [14]:
arm.get_GP_position_at_angles(
    np.array([0, np.pi/2, np.pi/2, np.pi])
)

array([-1.0000000e+00,  1.2246468e-16,  6.0000000e+00])

In [15]:
angles = range_limiter_vector.function([0,0,0,0])
angles

array([3.14159265, 1.57079633, 1.57079633, 1.57079633])

In [16]:
np.array([0, np.pi/2, np.pi/2, np.pi/2])

array([0.        , 1.57079633, 1.57079633, 1.57079633])

In [17]:
arm.get_GP_position_at_angles(angles)

array([0., 0., 7.])

In [18]:
desired_position = np.array([0., 0., 7.])
angles_estimate = arm.get_angles_for_GP_position(desired_position)
achieved_position = arm.get_GP_position_at_angles(angles_estimate)
achieved_position

array([0., 0., 7.])

In [19]:
some_angles = np.array([np.pi/4, np.pi/2, np.pi/2, 0.01])
desired_position = arm.get_GP_position_at_angles(some_angles)
desired_position

array([0.70707143, 0.70707143, 6.00999983])

In [20]:
angles_estimate = arm.get_angles_for_GP_position(desired_position, echo=False)
achieved_position = arm.get_GP_position_at_angles(angles_estimate)
achieved_position

Iteration 0:
Current angles are:   [3.1416, 1.7013, 1.7013, 1.7013]
Current position is:  [0.0, 0.0, 7.0]
Current loss is:  1.9800003333316667
Iteration 1:
Current angles are:   [3.5369, 1.7359, 1.7501, 1.7634]
Current position is:  [1.2886, 0.0, 6.831]
Current loss is:  1.5120598037748063
Iteration 2:
Current angles are:   [3.911, 1.7128, 1.7453, 1.7786]
Current position is:  [1.5502, 0.6469, 6.701]
Current loss is:  1.1920071813774158
Iteration 3:
Current angles are:   [4.0989, 1.6896, 1.7336, 1.7813]
Current position is:  [1.1115, 1.0765, 6.7363]
Current loss is:  0.8274483448272417
Iteration 4:
Current angles are:   [4.1736, 1.6744, 1.7288, 1.7906]
Current position is:  [0.7965, 1.1313, 6.7815]
Current loss is:  0.7831608672651208
Iteration 5:
Current angles are:   [4.1985, 1.6626, 1.7278, 1.8051]
Current position is:  [0.6621, 1.1076, 6.8022]
Current loss is:  0.7900414164790087
Iteration 6:
Current angles are:   [4.1988, 1.6525, 1.7287, 1.8229]
Current position is:  [0.6058, 1.07

array([0.70706863, 0.70730766, 6.01025483])

# I think the above is a great example of a local minima. I think it is locally if change the j component without increasing loss.
# I will try adding in the tries mechanism to fix this

In [21]:
some_angles = np.array([np.pi/3, 4*np.pi/5, np.pi/7, 3*np.pi/4])
some_angles

array([1.04719755, 2.51327412, 0.44879895, 2.35619449])

In [22]:
desired_position = arm.get_GP_position_at_angles(some_angles)
desired_position

array([-1.31971084, -2.28580623,  5.55321701])

In [23]:
angles_estimated_from_position = arm.get_angles_for_GP_position(desired_position)
angles_estimated_from_position

array([1.0327706 , 1.70628507, 2.09861234, 2.49749187])

In [24]:
resulting_position = arm.get_GP_position_at_angles(angles_estimated_from_position)
resulting_position

array([-1.35104615, -2.26401025,  5.52922696])