In [1]:
from arm import *

In [2]:
range_limiter = do.Range_Limiter_Scalar(0, np.pi)

In [3]:
range_limiter.map_scalar_to_target_interval(-100)

1.1686963357062937e-43

In [4]:
range_limiter.map_scalar_to_target_interval(100)

3.141592653589793

In [5]:
range_limiter.derivative_of_mapping(10)

0.00014260866166367913

In [6]:
range_limiter.derivative_of_mapping(0)

0.39269908169872414

In [7]:
range_limiter.derivative_of_mapping(-5)

0.00013978344426319542

In [8]:
range_limiter_vector = do.Range_Limit_Vector((
    (0, 2*np.pi),
    (0, np.pi),
    (0, np.pi),
    (0, np.pi),
))

In [9]:
range_limiter_vector.function(
    np.array([0,0,0,0])
)

array([3.14159265, 1.57079633, 1.57079633, 1.57079633])

In [10]:
range_limiter_vector.derivative_WR_vector(
    np.array([0,0,0,0])
)

array([[0.78539816, 0.        , 0.        , 0.        ],
       [0.        , 0.39269908, 0.        , 0.        ],
       [0.        , 0.        , 0.39269908, 0.        ],
       [0.        , 0.        , 0.        , 0.39269908]])

In [11]:
arm = Leipzig_Robot_Arm()

In [12]:
arm.get_GP_position_at_angles(
    np.array([0, np.pi/2, np.pi/2, np.pi/2])
)

array([0., 0., 7.])

In [13]:
arm.get_GP_position_at_angles(
    np.array([np.pi, np.pi/2, np.pi/2, np.pi/2])
)

array([0., 0., 7.])

In [14]:
arm.get_GP_position_at_angles(
    np.array([0, np.pi/2, np.pi/2, np.pi])
)

array([-1.0000000e+00,  1.2246468e-16,  6.0000000e+00])

In [15]:
angles = range_limiter_vector.function([0,0,0,0])
angles

array([3.14159265, 1.57079633, 1.57079633, 1.57079633])

In [16]:
np.array([0, np.pi/2, np.pi/2, np.pi/2])

array([0.        , 1.57079633, 1.57079633, 1.57079633])

In [17]:
arm.get_GP_position_at_angles(angles)

array([0., 0., 7.])

In [18]:
desired_position = np.array([0., 0., 7.])
angles_estimate = arm.get_angles_for_GP_position(desired_position, echo_level = 2)
achieved_position = arm.get_GP_position_at_angles(angles_estimate)
achieved_position

Iteration 0: Current loss is:  0.0
Iteration 10: Current loss is:  0.0
Iteration 20: Current loss is:  0.0
Iteration 30: Current loss is:  0.0
Iteration 40: Current loss is:  0.0
Iteration 50: Current loss is:  0.0
Iteration 60: Current loss is:  0.0
Iteration 70: Current loss is:  0.0
Iteration 80: Current loss is:  0.0
Iteration 90: Current loss is:  0.0
Iteration 100: Current loss is:  0.0
Iteration 110: Current loss is:  0.0
Iteration 120: Current loss is:  0.0
Iteration 130: Current loss is:  0.0
Iteration 140: Current loss is:  0.0
Iteration 150: Current loss is:  0.0
Iteration 160: Current loss is:  0.0
Iteration 170: Current loss is:  0.0
Iteration 180: Current loss is:  0.0
Iteration 190: Current loss is:  0.0
Starting Angles: [3.1416, 1.5708, 1.5708, 1.5708]:
Current Angles are:  [3.1416, 1.5708, 1.5708, 1.5708]
Desired position is:  [0.0, 0.0, 7.0]
Current position is:  [0.0, 0.0, 7.0]
Current loss is:  0.0


array([0., 0., 7.])

In [19]:
some_angles = np.array([np.pi/4, np.pi/2, np.pi/2, 0.01])
desired_position = arm.get_GP_position_at_angles(some_angles)
desired_position

array([0.70707143, 0.70707143, 6.00999983])

In [20]:
angles_estimate = arm.get_angles_for_GP_position(desired_position, echo_level = 2)
achieved_position = arm.get_GP_position_at_angles(angles_estimate)
achieved_position

Iteration 0: Current loss is:  1.9800003333316667
Iteration 10: Current loss is:  0.697219739737224
Iteration 20: Current loss is:  0.42240214153820543
Iteration 30: Current loss is:  0.18791475172458744
Iteration 40: Current loss is:  0.07541043859645866
Iteration 50: Current loss is:  0.030794164593699724
Iteration 60: Current loss is:  0.012811679337369406
Iteration 70: Current loss is:  0.00537345945600134
Iteration 80: Current loss is:  0.002259249104720868
Iteration 90: Current loss is:  0.0009501948451508292
Iteration 100: Current loss is:  0.0003995592291791692
Iteration 110: Current loss is:  0.00016801613327731575
Iteration 120: Current loss is:  7.06897874851184e-05
Iteration 130: Current loss is:  2.9783790241312538e-05
Iteration 140: Current loss is:  1.258488544789244e-05
Iteration 150: Current loss is:  5.346634399052554e-06
Iteration 160: Current loss is:  2.2949669292970263e-06
Iteration 170: Current loss is:  1.0046244955921524e-06
Iteration 180: Current loss is:  4.5

array([0.70706863, 0.70730766, 6.01025483])

# I think the above is a great example of a local minima. I think it is locally if change the j component without increasing loss.
# I will try adding in the tries mechanism to fix this

In [21]:
some_angles = np.array([np.pi/3, 4*np.pi/5, np.pi/7, 3*np.pi/4])
some_angles

array([1.04719755, 2.51327412, 0.44879895, 2.35619449])

In [22]:
desired_position = arm.get_GP_position_at_angles(some_angles)
desired_position

array([-1.31971084, -2.28580623,  5.55321701])

In [23]:
angles_estimated_from_position = arm.get_angles_for_GP_position(desired_position, echo_level=2)
angles_estimated_from_position

Iteration 0: Current loss is:  9.059727861736029
Iteration 10: Current loss is:  0.2354662252868815
Iteration 20: Current loss is:  0.1646505773162986
Iteration 30: Current loss is:  0.07099693919076487
Iteration 40: Current loss is:  0.03460556748398521
Iteration 50: Current loss is:  0.08021243922940872
Iteration 60: Current loss is:  0.08686303616600066
Iteration 70: Current loss is:  0.035168088167101125
Iteration 80: Current loss is:  0.05423098286518771
Iteration 90: Current loss is:  0.0497566759581251
Iteration 100: Current loss is:  0.017069148532930976
Iteration 110: Current loss is:  0.014943057159971608
Iteration 120: Current loss is:  0.026349295267322992
Iteration 130: Current loss is:  0.015619929085124927
Iteration 140: Current loss is:  0.00845979565720275
Iteration 150: Current loss is:  0.014585566900106399
Iteration 160: Current loss is:  0.008765917779985907
Iteration 170: Current loss is:  0.003184219648856689
Iteration 180: Current loss is:  0.005900178835619824


array([1.0327706 , 1.70628507, 2.09861234, 2.49749187])

In [24]:
resulting_position = arm.get_GP_position_at_angles(angles_estimated_from_position)
resulting_position

array([-1.35104615, -2.26401025,  5.52922696])